### ISSUE TITLE
[Feature] automatically match diameter

### ISSUE THREAD

**Issue by BloodyRain2k** [Starwaster/ProceduralParts#13]
Would it be possible to get the procedural tanks to automatically match their diameter when being attached?

Like when you take a new procedural tank and place it below a S2 decoupler that it'd automatically set itself to 2.5m diameter?

**Comment by Starwaster** [comment]
Probably, but I think it's more a question of how that can be done while still allowing players control over the size of the tank. Deliberate resizing should always take precedence over automatic sizing.

**Comment by HebaruSan** [comment]
This is a feature of SmartTank, just released. There's a toggle in the part right click menu to control whether the size is manual or automatic, and a global setting to control that toggle for new parts.

http://forum.kerbalspaceprogram.com/index.php?/topic/162743-130-smarttank-v010/

**Comment by Starwaster** [comment]
Closing issue as @HebaruSan has a mod that addresses it.
