### ISSUE TITLE
my lft has no fuel in it?

### ISSUE THREAD

**Issue by 0sj** [Starwaster/ProceduralParts#15]
i would like to know why this is, because this mod is awsome and i "need" it

**Comment by Starwaster** [comment]
I have no idea why that is because it works for me, and you aren't giving me any information at all that would facilitate troubleshooting. I need logs and your Module Manager cache file or I can't help. Sorry.

**Comment by Starwaster** [comment]
Closing this issue. If you have more information for me later, feel free to re-open.
