### ISSUE TITLE
Spontaneous explosion on quickload or vessel switch.

### ISSUE THREAD

**Issue by tivec** [Starwaster/ProceduralParts#18]
Today I have been struggling to find out what was causing numerous exceptions like this one when loading a quicksave or switching to certain vessels, leading to exploding craft:

> [EXC 12:56:24.512] NullReferenceException: Object reference not set to an instance of an object
> 	PartJoint.SetupJoint (Vector3 jointPos, Vector3 jointOrt, Vector3 jointOrt2, Int32 size)
> 	PartJoint.create (.Part child, .Part parent, UnityEngine.Transform nodeSpace, Vector3 nodePos, Vector3 nodeOrt, Vector3 nodeOrt2, Int32 nodeSize, AttachModes mode, Boolean rigid)
> 	PartJoint.Create (.Part owner, .Part parent, .AttachNode nodeToParent, .AttachNode nodeFromParent, AttachModes mode)
> 	Part.SecureAutoStrut (.Part anchor)
> 	Part+<SecureAutoStruts>c__Iterator3D.MoveNext ()
> 	UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

My first suspicion was my use of autostruts (Editor Extensions, mass tweakable set autostrut to root part), so I set them all to disabled, and this seemed to have solved the issue. 

However, I dug through the log file and found this:

> [WRN 12:56:24.206] BoxColliders does not support negative scale or size.
> The effective box size has been forced positive and is likely to give unexpected collision geometry.
> If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "proceduralBattery"

I removed the procedural battery and set autostrut on all to root, and had no more issues with explosions over several quicksave/quickload cycles.

Tests I have run so far:
- Set entire vessel to AS Root - no procedural parts.
  - Add a procedural battery anywhere on the vessel. Do not set autostrut.
  - Load vessel to runway. Quicksave, quickload => Explosion.

- Set entire vessel to AS Root - no procedural parts.
  - Add a procedural tank anywhere on the vessel. Do not set autostrut.
  - Load vessel to runway. Quicksave, quickload => Explosion.

- Set entire vessel to AS Disabled - no procedural parts.
  - Add a procedural tank anywhere on the vessel. Set autostrut to root part
  - Load vessel to runway. Quicksave, quickload => No explosion.

This seems to be a problem with autostrut in conjunction with the negative scaling on the MeshCollider.

[KSP - Autostrut partjoint - negative scale collider.zip](https://github.com/Starwaster/ProceduralParts/files/1148200/KSP.-.Autostrut.partjoint.-.negative.scale.collider.zip)

Attached is the log file if you wish to investigate. I see a lot of other mods with negative scale colliders, but I can recreate this very easily with ProceduralParts.

**Comment by Starwaster** [comment]
Try replacing the ProceduralParts.dll file with the one linked below (the file is located in GameData/ProceduralParts/Plugins/)

https://www.dropbox.com/s/8385vooo95i6c5m/ProceduralParts.dll?dl=1

Retest and re-send new log file if problem persists

Also send craft file for me to try to repro the problem with (stock parts + PP parts only)

**Comment by tivec** [comment]
Hey,

The inverted collider bug seems to be gone, but on my original craft there are still spontaneous explosions when quickloading the vessel.

I built a simple craft with just squad parts to test with, but have so far been unable to reproduce the exploding issue. On inspection of the log, I do still get the PartJoint.SetupJoint NullReferenceExceptions, but there are no explosions.

I will keep trying to see if I can provoke an explosion with stock and PP parts only, but suspect the problem lies elsewhere now.

**Comment by Starwaster** [comment]
Closing issue as the changes made fixed the issue with the exception of the saved craft?

**Comment by Starwaster** [comment]
And fix will be in next update. (and should be in whoever's branch that forked my branch and actually has their branch on CKAN now)
