### ISSUE TITLE
No lower SRB burn time limit when using RealFuels

### ISSUE THREAD

**Issue by rsparkyc** [Starwaster/ProceduralParts#2]
This pretty much duplicates https://github.com/Swamp-Ig/ProceduralParts/issues/202, but wanted to add more issues.
It looks like the `maxThrust` variable here is being set to infinity:
https://github.com/Starwaster/ProceduralParts/blob/master/Source/ProceduralSRB.cs#L601
That's because the `attachedEndSize` variable here is infinity: https://github.com/Starwaster/ProceduralParts/blob/master/Source/ProceduralSRB.cs#L586
This should be set in this function, but I'm never seeing that get called: https://github.com/Starwaster/ProceduralParts/blob/master/Source/ProceduralSRB.cs#L154

**Comment by Starwaster** [comment]
ok, I think what's happening here is... that function is supposed to be called as part of an event and there's no event defined anywhere. (previous incarnations of that function had explicit arguments listing the attach node, the area and min diameter - now it's got only a single event data arg)

I'm going to try adding the event as it exists in other procedural classes and see how that works out

**Comment by Starwaster** [comment]
Ah no, scratch that... the rest of the classes that have a function like that DO have explicit args? Hrmmmm.... maybe ProceduralSRB was meant to be a child class of something else? Have to tear this apart some more... sigh.

**Comment by Starwaster** [comment]
Closing issue; fixed in latest release
