### ISSUE TITLE
Procedural SRB gimbal is about only one-axis.

### ISSUE THREAD

**Issue by Lookerksy** [Starwaster/ProceduralParts#23]
First I set "gimbalRange" to 20 in cfg file.
Then I found the nozzle action only was responsive to one of pitch or yaw control.
It seems that the gimbal is only about one-axis. Is it a BUG of FEATURE?
I think it  shall be about two-axis.
![default](https://user-images.githubusercontent.com/21987795/33896902-0bb413ec-df9f-11e7-908e-3ff866d1c6ac.png)

**Comment by Starwaster** [comment]
Bug. Known issue.

**Comment by Starwaster** [comment]
Fixed next update
