### ISSUE TITLE
Part Costs

### ISSUE THREAD

**Issue by FuriousSquirrel** [Starwaster/ProceduralParts#24]
So I noticed in many on the configs files the part costs have been edited out by the quote slashes. Overall, the prices also get modified but I'm still very new to figuring out how to work the files. It seems a bit messy right now but I think this is something that needs adjustment. It seems relatively easy and for the most part I can figure it out. Like I said though, I'm new to Github, I only dabble in code, but Googling helps a lot and I learn fast. Anyone able to assist me with this to fix?

**Comment by Starwaster** [comment]
What do you think needs fixing? The costs (along with a lot of everything else) are determined procedurally.  Of all the things this mod needs, the configs are probably the last things. Don't worry about what is commented out.

**Comment by FuriousSquirrel** [comment]
It weird because I got some odd costs associated. The only part that seems to scale correctly cost wise is the SRBs. The heatshield costs $14,778.74. The proc tanks cost 0.01, and all the other procedural parts cost 0. I guess I can see about testing this mod on a non modded KSP to check for conflicts. I'll give that a go and come back with results.

**Comment by FuriousSquirrel** [comment]
Sorry about all the back and forth. I'm sure the last thing you want to deal with is a guy trying to get to the bottom of an unimportant issue. I isolated the mod and the game and the issue persists with all but the SRBs. Even with real fuels the RF tanks are also having similar issues.

**Comment by Starwaster** [comment]
You don't say how large you scaled that shield so I have no idea if what you saw is normal or not. A 15 meter shield would approach that kind of pricing due to how much ablative material it has.

**Comment by FuriousSquirrel** [comment]
The default size. All I did was select it. It's the pricing that shows in the description and also when loaded, the same pricing appears for the rocket total cost. It's awfully strange.

**Comment by Starwaster** [comment]
I need your output_log.txt file and your ModuleManager.ConfigCache (The latter file is in GameData folder) and a screenshot of the part being viewed in the parts list with the description showing please
