### ISSUE TITLE
Procedural Tanks No Longer Auto-Updates With Resources

### ISSUE THREAD

**Issue by RealKolago** [Starwaster/ProceduralParts#26]
Can you help fixing this:
https://github.com/allista/ConfigurableContainers/issues/23

**Comment by Starwaster** [comment]
Can I help fixing a mod compatibility problem with a Procedural Parts branch someone else made because I haven't been able to find the time to update _my own_ branch to the latest KSP? Right, no problem...

**Comment by Starwaster** [comment]
Closing this as it's not an issue with this branch of Procedural Parts.
